name: etl-prod
services:
  etlscripts:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - DB_HOST=${DB_HOST?REQUIRED}
      - DB_PORT=${DB_PORT?REQUIRED}
      - DB_USER=${DB_USER?REQUIRED}
      - DB_PASSWORD=${DB_PASSWORD?REQUIRED}
      - DB_DATABASE=${DB_DATABASE?REQUIRED}